name: dharavikabhoot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: Consolas
      fonts:
        - asset: assets/Consolas.ttf
        - asset: assets/CONSOLAB.TTF
          weight: 700
        - asset: assets/consolai.ttf
          style: italic
        - asset: assets/CONSOLA.TTF
        - asset: assets/consolaz.ttf
          weight: 900
